version: "3.8"

services:
  db:
    image: postgres:14
    container_name: blu_reserve_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blu_reserve
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blu_reserve
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: