version: "3.8"

services:
  db:
    image: postgres:14
    container_name: blu_reserve_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blu_reserve
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blu_network

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blu_reserve
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - blu_network

  user_management_service:
    build:
      context: ./services/user_management
    container_name: user_management_service
    environment:
      DB_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blu_reserve
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - blu_network

  health_service:
    build:
      context: ./services/health_service
    container_name: health_service
    ports:
      - "8005:8005"
    depends_on:
      - auth_service
      - user_management_service
    networks:
      - blu_network

  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - auth_service
      - user_management_service
      - health_service
    networks:
      - blu_network

volumes:
  db_data:

networks:
  blu_network:
    driver: bridge
